---
language: python
services: docker

env:
  global:
    - ROLE_NAME: ansible-role-demo
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos6

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.

script:
  # Run tests.
  - molecule test
